POST http://localhost:3000/user/signup
Content-Type: application/json

{
    "email": "something@gmail.com",
    "password": "password12"
}

### 

POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "password"
}

### 

POST http://localhost:3000/user/add-contact
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzAzYjkyODA2ZjI3YzExNmI1ZmQ4MjkiLCJlbWFpbCI6InNvbWV0aGluZ0BnbWFpbC5jb20iLCJpYXQiOjE2NjExODgzOTIsImV4cCI6MTY2MTE5MDE5Mn0.f65svvdjY_579v9PmfgGrtPGyRs4TAPTXGfNSvZJCQI
Content-Type: application/json

{
    "firstName": "Fabian", 
    "lastName": "Guevara",
    "phone": "606390209",
    "address": "Somewhere over the rainbow"
}

### POST 