POST http://localhost:3000/user/signup
Content-Type: application/json

{
    "email": "fabiangviveros@gmail.com",
    "password": "password12"
}

### 

POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email": 1,
    "password": "password"
}

### 

POST http://localhost:3000/user/add-contact
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzAzNmJlYjFlYzZiMmY0Yjg3ZmI4YTUiLCJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJpYXQiOjE2NjExNzM5NzcsImV4cCI6MTY2MTE3NTc3N30.b0uWZPwR7fMS90AR9QqEbYXfVS5vBrkiQEXXBAL8OG4
Content-Type: application/json

{
    "firstName": "Fabian", 
    "lastName": "Guevara",
    "phone": "606390209",
    "address": "Somewhere over the rainbow"
}

### POST 